apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: {{ .Values.ollama.servicePort }}
    targetPort: {{ .Values.ollama.servicePort }}