apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-webui-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-webui
  template:
    metadata:
      labels:
        app: ollama-webui
    spec:
      containers:
      - name: ollama-webui
        image: ghcr.io/ollama-webui/ollama-webui:main
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: OLLAMA_API_BASE_URL
          value: "http://ollama-service.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.ollama.servicePort }}/api"
        tty: true