services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}


  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/c0sogi/open-webui:${OPEN_WEBUI_DOCKER_TAG-latest}
    container_name: open-webui
    volumes:
      - /app/backend/data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 80:8080
    environment:
      - 'WEBUI_NAME=${WEBUI_NAME-T-intelligence}'
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}