# docker compose -f docker-compose.yaml -f docker-compose.gpu.yaml up -d --build
# docker compose -f docker-compose.yaml -f docker-compose.gpu.yaml up -d
services:
  ollama:
    volumes:
      - ./domainExpansion/ollama:/root/.ollama  # Bind mount within the domainExpansion directory
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ./domainExpansion/open-webui:/app/backend/data  # Bind mount within the domainExpansion directory
      # - ./domainExpansion/docs:/data/docs  # Mount the docs directory within the domainExpansion directory
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  ollama: {}
  open-webui: {}
