name: open-webui-dev

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  frontend:
    build:
      context: .
      target: build
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    # ports:
    #   - "3000:5173"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
    networks:
      - backend
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chat-frontend.rule=Host(`chat.matn.ai`)"
        - "traefik.http.routers.chat-frontend.entrypoints=websecure"
        - "traefik.http.routers.chat-frontend.tls.certresolver=myresolver"
        - "traefik.http.services.chat-frontend.loadbalancer.server.port=5173"


  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    env_file: .env
    environment:
     - ENV=dev
     - WEBUI_AUTH=True
     - WEBUI_SECRET_KEY=1cbcdc97bc1c47620317e943a38d02ce
     - ENABLE_SIGNUP=True
     - DEFAULT_USER_ROLE=user
     - MATN_CHARGE_API=https://matn.ai/dashboard/get_chatuser_charge
    #  - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-User-Email
    #  - ADMIN_EMAIL=saman.esmaeil@zohomail.com
    #  - WEBUI_AUTH_TRUSTED_NAME_HEADER=chat-matn-ai
    volumes:
      - data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - backend/data
        - action: rebuild
          path: backend/requirements.txt


  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - ./pipelines:/app/pipelines
      - ./blueprints:/app/blueprints
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  data: {}
  ollama: {}

networks:
  backend:
    external: true