version: '3.8'

services:
  sentient-sculptor:
    container_name: sentient-sculptor
    build:
      context: .  # Path to your Dockerfile or project
      dockerfile: Dockerfile  # Use Dockerfile in the same directory (customize as needed)
    volumes:
      - sentient-sculptor:/app/data  # Persistent data for the Sentient Sculptor model
    ports:
      - "5000:5000"  # Assuming the Sentient Sculptor model exposes an API on port 5000
    environment:
      - MODEL_PATH=/app/data/model.pth  # Path to the model file
      - TOKENIZER_PATH=/app/data/bpe_token.json  # Path to the tokenizer file
    restart: unless-stopped
    tty: true
    depends_on:
      - database  # Assuming there's a database for managing data (if necessary)
    networks:
      - sentient-network

  sentient-ui:
    container_name: sentient-ui
    build:
      context: .  # Assuming the frontend (web UI) is in the "ui" folder
      dockerfile: Dockerfile  # Use Dockerfile for the web UI
    ports:
      - "3000:3000"  # Frontend exposed on port 3000
    environment:
      - API_URL=http://sentient-sculptor:5000  # Connect the UI to the Sentient Sculptor API
    depends_on:
      - sentient-sculptor
    networks:
      - sentient-network

  database:
    container_name: sentient-db
    image: postgres:13  # Example database if Sentient Sculptor requires one
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=sentient_db
    restart: unless-stopped
    networks:
      - sentient-network

volumes:
  sentient-sculptor: {}
  db-data: {}

networks:
  sentient-network:
    driver: bridge
