version: '3.8'

services:
  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentient_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  sentient-sculptor:
    build:
      context: .
      args:
        USE_CUDA: ${USE_CUDA-false}
        USE_OLLAMA: ${USE_OLLAMA-false}
        USE_CUDA_VER: ${USE_CUDA_VER-cu121}
        USE_EMBEDDING_MODEL: ${USE_EMBEDDING_MODEL-sentence-transformers/all-MiniLM-L6-v2}
        USE_RERANKING_MODEL: ${USE_RERANKING_MODEL-""}
    container_name: sentient-sculptor
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/sentient_db
    ports:
      - '8000:8000'
    volumes:
      - sentient-sculptor:/app/data
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:80'
    restart: unless-stopped
    depends_on:
      - sentient-sculptor

volumes:
  db-data:
  sentient-sculptor:
