version: '3.6'

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
# To expose Ollama API outside the container stack, remove # from the next lines
#    ports:
#      - 11434:11434

# Remove # to enable GPU support (NVIDIA)
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities:
#                - gpu



  ollama-webui:
#  Make sure to comment out "image" if you want to built the image yourself. Use "image" to pull down an already compiled webui image.
#    build:
#      context: .
#      args:
#        OLLAMA_API_BASE_URL: '/ollama/api'
#      dockerfile: Dockerfile

#   Do not forget to comment out "image" if you are building your own image! 
    image: ollama-webui:latest
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  ollama-webui: {}
