apiVersion: apps/v1
kind: Deployment
metadata:
  name: Falcor-deployment
  namespace: Falcor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Falcor
  template:
    metadata:
      labels:
        app: Falcor
    spec:
      containers:
      - name: Falcor
        image: ghcr.io/Falcor/Falcor:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.Falcor.svc.cluster.local:11434"
        tty: true
        volumeMounts:
        - name: Falcor-volume
          mountPath: /app/backend/data
      volumes:
      - name: Falcor-volume
        persistentVolumeClaim:
          claimName: Falcor-pvc          