apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: Falcor
  name: Falcor-pvc
  namespace: Falcor
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi