nameOverride: ""

ollama:
  externalHost: "http://192.168.100.14:31774"
  # externalHost: "http://192.168.100.14:32383"
  annotations: {}
  podAnnotations: {}
  replicaCount: 1
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: Always
  resources: {}
  persistence:
    enabled: true
    size: 30Gi
    existingClaim: ""
    accessModes:
    - ReadWriteOnce
    storageClass: ""
    selector: {}
    annotations: {}
  nodeSelector: {}
  # -- If using a special runtime container such as nvidia, set it here.
  runtimeClassName: ""
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  service:
    type: ClusterIP
    annotations: {}
    port: 80
    containerPort: 11434
  gpu:
    # -- Enable additional ENV values to help Ollama discover GPU usage
    enabled: false

webui:
  enabled: false
  annotations: {}
  podAnnotations: {}
  replicaCount: 1
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: ""
    pullPolicy: Always
  resources: {}
  ingress:
    enabled: false
    class: ""
    # -- Use appropriate annotations for your Ingress controller, e.g., for NGINX:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    annotations: {}
    host: ""
    tls: false
    existingSecret: ""
  persistence:
    enabled: true
    size: 2Gi
    existingClaim: ""
    # -- If using multiple replicas, you must update accessModes to ReadWriteMany
    accessModes:
    - ReadWriteOnce
    storageClass: ""
    selector: {}
    annotations: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: NodePort
    annotations: {}
    port: 80
    containerPort: 8080
    nodePort: 31030
    labels: {}
    loadBalancerClass: "" 

hrwebui:
  enabled: true
  annotations: {}
  podAnnotations: {}
  replicaCount: 1
  image:
    repository: ghcr.io/ciai-engineering/open-webui
    tag: "git-c03c400"
    pullPolicy: Always
  resources: {}
  imagePullSecrets: 
    name: ragsecret
  ingress:
    enabled: false
    class: ""
    # -- Use appropriate annotations for your Ingress controller, e.g., for NGINX:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    annotations: {}
    host: ""
    tls: false
    existingSecret: ""
  persistence:
    enabled: true
    size: 2Gi
    existingClaim: ""
    # -- If using multiple replicas, you must update accessModes to ReadWriteMany
    accessModes:
    - ReadWriteOnce
    storageClass: ""
    selector: {}
    annotations: {}
  nodeSelector: {
    kubernetes.io/hostname: ciai-cpu-w05588
    }
  tolerations: []
  service:
    type: NodePort
    annotations: {}
    port: 80
    containerPort: 8080
    nodePort: 31031
    labels: {}
    loadBalancerClass: "" 
