name: Python CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: 'Format Backend'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: grep '^ruff' backend/requirements.txt | xargs python -m pip install

      - name: Format backend
        run: npm run format:backend
        env:
          RUFF_OUTPUT_FORMAT: github

      - name: Check for changes after format
        run: git diff --exit-code
